export const SERVICES = [
  {
    id: 1, slug: "graphic-design", icon: "◈",
    title: "Graphic Design",
    short: "Visual identities that command attention.",
    desc: "From brand identities to print campaigns, we craft visuals that stop the scroll and start conversations. Every pixel is intentional, every composition deliberate.",
    tags: ["Brand Identity", "Print", "Social Media", "Packaging", "Illustration"],
    color: "#FF4D00",
  },
  {
    id: 2, slug: "motion-graphics", icon: "◉",
    title: "Motion Graphics",
    short: "Ideas in motion. Stories in frames.",
    desc: "Kinetic typography, animated logos, explainer videos, and social content that moves audiences — literally. We breathe life into static concepts.",
    tags: ["Logo Animation", "Explainer Video", "Title Sequences", "Social Motion", "3D Elements"],
    color: "#7C3AED",
  },
  {
    id: 3, slug: "video-editing", icon: "▶",
    title: "Video Editing",
    short: "Raw footage transformed into cinema.",
    desc: "Color grading, pacing, sound design, and storytelling — we take your raw footage and turn it into compelling content that holds attention from first to last frame.",
    tags: ["Color Grading", "Documentary", "Commercial", "Social Cuts", "Long-Form"],
    color: "#0EA5E9",
  },
  {
    id: 4, slug: "branding", icon: "◎",
    title: "Brand Strategy",
    short: "Not just a logo. A full universe.",
    desc: "Complete brand systems — strategy, voice, visual language, guidelines, and rollout. We build brands that own their category and grow with your business.",
    tags: ["Strategy", "Naming", "Visual Identity", "Brand Guidelines", "Rollout"],
    color: "#10B981",
  },
  {
    id: 5, slug: "ui-design", icon: "▦",
    title: "UI/UX Design",
    short: "Interfaces people fall in love with.",
    desc: "Digital product design that balances aesthetics with function. Wireframes, prototypes, and polished UI systems for web and mobile platforms.",
    tags: ["Web Design", "Mobile UI", "Prototyping", "Design Systems", "UX Research"],
    color: "#F59E0B",
  },
  {
    id: 6, slug: "content-creation", icon: "⬡",
    title: "Content Creation",
    short: "Content that converts.",
    desc: "Strategy-driven content for social media, campaigns, and brand storytelling. Photography direction, copywriting, and full production support.",
    tags: ["Social Media", "Photography Dir.", "Copywriting", "Campaigns", "Strategy"],
    color: "#EC4899",
  },
];
